PagoAseoWeb/Controllers/InicioController.cs
using SocialAseoWeb.Comun;
using SocialAseoWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SocialAseoWeb.Controllers;
using Word = Microsoft.Office.Interop.Word;
using System.IO;
using Aspose.Words;
using Aspose.Words.Saving;
using System.Text;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net;

namespace SocialAseoWeb.Controllers
{
    public class InicioController : Controller
    {
        //
        // GET: /Inicio/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Inicio/Details/5
    
        [HttpGet]
        public PartialViewResult ListarRol(string rol, string dv)
        {
            List<AS_CONVENIO> deudas = new List<AS_CONVENIO>();

            using (aseoEntities entidadesAseo = new aseoEntities())
            {
                decimal numRol = Convert.ToDecimal(rol);
                decimal numDv = Convert.ToDecimal(dv);
                var Resp = (from Tconv in entidadesAseo.AS_CONVENIO
                            from TPag in entidadesAseo.AS_PAGOS
                            where Tconv.CON_ANO_CON == (DateTime.Now.Year - 2) &&
                                    Tconv.CON_ROL_NUM == numRol &&
                                    Tconv.CON_ROL_DV == numDv &&
                                    Tconv.CON_ANO_CON == TPag.PAG_ANO_CON &&
                                    Tconv.CON_ROL_NUM == TPag.PAG_ROL_NUM &&
                                    Tconv.CON_ROL_DV == TPag.PAG_ROL_DV &&
                                    Tconv.CON_CUOTA == TPag.PAG_CUOTA &&
                                    Tconv.CON_CODEX == 8
                            select Tconv).ToList();
                deudas.AddRange(Resp);
                var Resp1 = (from Tconv in entidadesAseo.AS_CONVENIO
                             from TPag in entidadesAseo.AS_PAGOS
                             where Tconv.CON_ANO_CON == (DateTime.Now.Year - 1) &&
                                     Tconv.CON_ROL_NUM == numRol &&
                                     Tconv.CON_ROL_DV == numDv &&
                                     Tconv.CON_ANO_CON == TPag.PAG_ANO_CON &&
                                     Tconv.CON_ROL_NUM == TPag.PAG_ROL_NUM &&
                                     Tconv.CON_ROL_DV == TPag.PAG_ROL_DV &&
                                     Tconv.CON_CUOTA == TPag.PAG_CUOTA &&
                                     Tconv.CON_CODEX == 8
                             select Tconv).ToList();
                deudas.AddRange(Resp1);
                var Resp2 = (from Tconv in entidadesAseo.AS_CONVENIO
                             from TPag in entidadesAseo.AS_PAGOS
                             where Tconv.CON_ANO_CON == (DateTime.Now.Year) &&
                                     Tconv.CON_ROL_NUM == numRol &&
                                     Tconv.CON_ROL_DV == numDv &&
                                     Tconv.CON_ANO_CON == TPag.PAG_ANO_CON &&
                                     Tconv.CON_ROL_NUM == TPag.PAG_ROL_NUM &&
                                     Tconv.CON_ROL_DV == TPag.PAG_ROL_DV &&
                                     Tconv.CON_CUOTA == TPag.PAG_CUOTA &&
                                     TPag.PAG_FEC_P == null &&
                                     (Tconv.CON_CODEX <= 4 || Tconv.CON_CODEX == 8)

                             select Tconv).ToList();

                deudas.AddRange(Resp2);
                           


                    var data = entidadesAseo.AS_CONTRIBUYENTE.Where(x => x.CON_ROL_NUM == numRol && x.CON_ROL_DV == numDv).FirstOrDefault();

                    if (data != null)
                    {
                        var nombre = entidadesAseo.AS_RUT.Where(x => x.RUT_RUT == data.CON_RUT).Select(x => x.RUT_NOMBRE).FirstOrDefault();
                        ViewBag.nombre = nombre;
                        ViewBag.direccion = data.CON_CALLE;
                        ViewBag.rutCont = data.CON_RUT + "-" + data.CON_DV;
                    }

                
            }
            return PartialView(deudas);
        }
        public JsonResult VerificaRol(string rol, string dv)
        {
            LogReg log = new LogReg();

            decimal numRol = 0;
            decimal numDv = 0;
            string rolLog = rol + "-" + dv;
            //List<AS_PAGOS> deudas = new List<AS_PAGOS>();

            try
            {
                log.abrirArchivo(rolLog);
                log.registrar("*********************************************");
                log.registrar(" * PROCESO: VerificaExiste");
                log.registrar("*********************************************");
                bool valRol = decimal.TryParse(rol, out numRol);
                bool valDv = decimal.TryParse(dv, out numDv);
                if (valRol == false || valDv == false)
                {
                    return Json("El rol se compone de números. Debe Ingresar datos validos.");
                }


                using (aseoEntities entidadesAseo = new aseoEntities())
                {

                    //var d = entidadesAseo.AS_PAGOS.Where(x => x.PAG_FEC_P == null && x.PAG_ROL_NUM == numRol && x.PAG_ROL_DV == numDv && x.PAG_MARCA != "C").ToList();
                    var data = entidadesAseo.AS_CONTRIBUYENTE.Where(x => x.CON_ROL_NUM == numRol && x.CON_ROL_DV == numDv).FirstOrDefault();

                    if (data != null)
                    {
                        return Json(new Object());
                    }
                    else
                    {
                        return Json("El rol no existe en registro del municipio. Debe Ingresar datos validos.");
                    }
             
                    
                }

            }
            catch (Exception ex)
            {
                string ns = this.ControllerContext.Controller.GetType().Namespace;
                string controller = this.ControllerContext.RouteData.Values["controller"].ToString();
                string action = this.ControllerContext.RouteData.Values["action"].ToString();
                //ManejoErrores(ns, controller, action, ex, log);
            }
            return Json("No hay una deuda asociada con el Rol ingresado.");

        }
       
        public ActionResult ConfirmarRol()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ConfirmarRol(FormCollection form, HttpPostedFileBase uploadRut)
        {
            LogReg log = new LogReg();
            Social_OrdenIngresoAseo oi = new Social_OrdenIngresoAseo();
            List<Social_DetalleOrdenIngresoAseo> exencion = new List<Social_DetalleOrdenIngresoAseo>();
            AS_CONTRIBUYENTE contr = new AS_CONTRIBUYENTE();
            AS_RUT rutContr = new AS_RUT();
            AS_CONVENIO ap2 = null;
               
            if (form.Count != 0)
            {      
                string rolLog = form["rolA"].ToString() + "-" + form["rolB"].ToString();
                string email = form["email"].ToString();
                string telefono = form["telefono"].ToString();
                string[] arrayRow2 = form["rut"].ToString().Split('-');
                string rut = arrayRow2[0].ToString();
                string dv = arrayRow2[1].ToString();
                string nombre = form["nombre"].ToString().ToUpper();
                string direccion = form["direccion"].ToString().ToUpper();
                string block = form["block"].ToString();
                decimal numero =  decimal.Parse(form["numero"].ToString());
                decimal rolNum = decimal.Parse(form["rolA"].ToString());
                decimal rolDv = decimal.Parse(form["rolB"].ToString());
                decimal anio = DateTime.Today.Year;
                decimal? Nsolicitud = 0;
                int conteo = 0;

                try
                {
                    log.abrirArchivo(rolLog);
                    log.registrar("*********************************************");
                    log.registrar(" * PROCESO: ConfirmarExentos");
                    log.registrar("*********************************************");
                    log.registrar(" * ROL: " + rolLog.ToString());
                    log.registrar(" * MAIL: " + email.ToString());
                    log.registrar(" * FONO: " + telefono.ToString());
                    //se busca folio solicitud dísponible


                    AS_SOLICITUD ia = null;
                     using (aseoEntities entidadAseo = new aseoEntities())
                                {
                                   ia = entidadAseo.AS_SOLICITUD.Where(x => x.SOL_TIPO.Equals("S")).FirstOrDefault();
                                   if (ia == null)
                                   {
                                       log.registrar("no existe el folio o no esta cargado");                                   
                                   }
                                   else
                                   {                              
                                       ia.SOL_NUM_SOL = ia.SOL_NUM_SOL + 1;
                                       entidadAseo.SaveChanges();
                                       Nsolicitud = ia.SOL_NUM_SOL;
                                   }                                  
                     

                     HttpFileCollectionBase file = Request.Files;
                     string fecha = DateTime.Now.ToString("yyyyMMdd");
                     string RutFuncionario = form["rut"].ToString();
                     uploadRut = file.Get("uploadRut");
                     string archNombre = (uploadRut.FileName).ToLower();
                     archNombre = rolNum +"-"+ rolDv +"_"+ rut + ".PDF";
                     string ruta = Server.MapPath("~/UploadedFiles") + "\\" + rut + "\\";
                     Utils.crearDirectorio(ruta);

PagoAseoWeb/Views/Inicio/ConfirmarRol.cshtml
@{
    ViewBag.Title = "ConfirmarRol";
    var usuario = Session["usuario"];
}
@*************************** modal para errores ********************************@
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id="modColHeader" class="modal-header-info">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 id="modTitulo" class="modal-title"></h4>
            </div>
            <div id="modColBody" class="modal-body">
                <p id="modBody"></p>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>

@*************************** formulario busqueda ********************************@
<div class="container">
    <div class="row">

        <div id="empresaRegistrada" class="content" style="display: block;">
            <div class="row text-center">
                <div class="col-md-12">
                    <p class="tituloH2">SOLICITUD DE EXENCION @usuario</p>
                </div>
            </div>
            <p id="mensaje"></p>
            @using (Html.BeginForm("ConfirmarRol", "inicio", FormMethod.Post, new { name = "exencionForm", id = "exencionForm", enctype = "multipart/form-data" }))
                {
                <div class="row">
                    <div class="col-md-1">
                    </div>
                    <div class="col-md-10">

                        <div id="DatContribuyente" class="panel panel-default">
                            <div class="panel-heading">Datos para exencion</div>
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-md-3">Se certifica que don(ña)</div>
                                    <div class="col-md-9"><input type="text" class="form-control" id="nombre" name="nombre" value="" required onkeyup="javascript:this.value=this.value.toUpperCase();"></div>
                                </div>
                                <br />
                                <div class="row">
                                    <div class="col-md-3">RUT N°</div>
                                    <div class="col-md-3"><input class="form-control" type="text" id="rut" name="rut" value=""></div>
                                    <div class="col-md-2">ROL N°</div>
                                    <div class="col-md-2"><input class="form-control" type="text" id="rolA" name="rolA" value=""></div>
                                    <div class="col-md-2"><input class="form-control" type="text" id="rolB" name="rolB" value=""></div>
                                </div>
                                <br />
                                <div class="row">
                                    <div class="col-md-2">Domicilio</div>
                                    <div class="col-md-3"><input class="form-control" type="text" id="domicilio" name="domicilio" value="" onkeyup="javascript:this.value=this.value.toUpperCase();"></div>
                                    <div class="col-md-1">N°</div>
                                    <div class="col-md-2"><input class="form-control" type="text" id="numero" name="numero" value=""></div>
                                    <div class="col-md-1">Block/Casa</div>
                                    <div class="col-md-1"><input class="form-control" type="text" id="block" name="block" value=""></div>
                                    <div class="col-md-1">Depto</div>
                                    <div class="col-md-1"><input class="form-control" type="text" id="depto" name="depto" value=""></div>
                                </div>
                                <br />
                                <div class="row">
                                    <div class="col-md-2">Domicilio RSH</div>
                                    <div class="col-md-3"><input class="form-control" type="text" id="domicilioRsh" name="domicilioRsh" value="" onkeyup="javascript:this.value=this.value.toUpperCase();"></div>
                                    <div class="col-md-1">N°</div>
                                    <div class="col-md-2"><input class="form-control" type="text" id="numeroRsh" name="numeroRsh" value=""></div>
                                    <div class="col-md-1">Block/Casa</div>
                                    <div class="col-md-1"><input class="form-control" type="text" id="blockRsh" name="blockRsh" value=""></div>
                                    <div class="col-md-1">Depto</div>
                                    <div class="col-md-1"><input class="form-control" type="text" id="deptoRsh" name="deptoRsh" value=""></div>
                                </div>
                                <br />
                                <div class="row">
                                    <div class="col-md-2">Conjunto Habitacional</div>
                                    <div class="col-md-7"><input class="form-control" type="text" id="conjunto" name="conjunto" value=""></div>
                                    <div class="col-md-1">U.V.</div>
                                    @*<div class="col-md-2"><input class="form-control" type="text" id="uv" name="uv" value=""></div>*@
                                    <div class="col-md-2">
                                        <select id="uv" name="uv" class="form-control">
                                            @for (var x = 1; x <= 20; x++)
                                            {
                                                <option value="@x">@x</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                                <br />
                                <div class="row">
                                    <div class="col-md-2">Fono</div>
                                    <div class="col-md-4"><input class="form-control" type="text" id="fono" name="fono" value=""></div>
                                    <div class="col-md-2">Email</div>
                                    <div class="col-md-4"><input class="form-control" type="text" id="email" name="email" value=""></div>
                                </div>
                                <br />
                                <div class="row">
                                    <div class="col-md-2">RSH Folio N°</div>
                                    <div class="col-md-4"><input class="form-control" type="text" id="folio" name="folio" value=""></div>
                                    <div class="col-md-2">Fecha</div>
                                    <div class="col-md-2"><input class="form-control" type="date" id="fecha" value="" name="fecha" min="2022-01-01" max="2022-12-31"></div>
                                    <script>

                                        date = new Date();
                                        let dia, month, year;
                                        dia = date.getDate();
                                        month = date.getMonth() + 1;
                                        year = date.getFullYear();
                                        var fecActual = year.toString() + "-" + largo(month) + "-" + largo(dia);
                                        document.getElementById("fecha").value = fecActual;
                                        function largo(input) {
                                            var nuevo = "";
                                            if (input.toString().length == 1) {
                                                nuevo = "0" + input;
                                                return nuevo;
                                            } else {
                                                nuevo =  input;
                                                return nuevo;
                                            }
                                        }
                                    </script>



                                    <div class="col-md-1">Tramo</div>
                                    <div class="col-md-1"><input class="form-control" type="text" id="tramo" name="tramo" value=""></div>
                                </div>
                                <br />
                                <div class="row">
                                    <div class="col-md-12">
                                        <h5 style="text-align:justify">Cumple los requisitos y será exento del pago de los derechos por el concepto de extraccion de basura domiciliaria por el periodo <label id="current_date"></label> según lo establecido en el Articulo N° 11 del decreto Alcaldicio N°1.529 del 22/12/2005 que dictó la Ordenanza Municipal y el Decreto Alcaldicio N° 1.119 del 30/07/2007 que lo complementa. 2016 D.A. 2288 16/08/2016.</h5>
                                        <br />
                                        <p style="font-size:16px ; text-align:center">Se extiende este certificado con la exclusiva finalidad de acreditar la exencion antes indicada sólo para el periodo <label id="current_date2"></label></p>
                                        <script>
                                            date = new Date();
                                            year = date.getFullYear();
                                            document.getElementById("current_date").innerHTML = year;
                                            document.getElementById("current_date2").innerHTML = year;
                                        </script>
                                        <p style="font-size:16px ; text-align:center">Las cuotas para exencion son: <label id="current_cuotas">.</label></p>
                                        <script>
                                            var data = "1,2,3 y 4";
                                            document.getElementById("current_cuotas").innerHTML = data;

                                        </script>
                                    </div>
                                </div>
                                <br />

                                <div class="row">


                                    @if (usuario != null)
                                    {
                                        <div class="col-md-1"></div>
                                        <div class="col-md-10"><input class="btn btn-danger btn-block" id="BtnGrabar" type="submit" value="Guardar Solicitud"></div>
                                        <div class="col-md-1"></div>
                                    }
                                    else
                                    {
                                        <div class="col-md-1"></div>

                                        <div class="col-md-10"><input class="btn btn-primary btn-block" id="BtnEnviar" type="submit" value="Enviar Solicitud"></div>
                                        <div class="col-md-1"></div>
                                    }
                                </div>

                            </div>
                        </div>
                    </div>
                    <div class="col-md-1">
                    </div>
                </div>
            }
        </div>
    </div>
</div>
@section scripts{
    <script type="text/javascript">
    var baseUrl = "";

    function validacion(campo) {

        miCampo = document.getElementById(campo).value;
        if (miCampo == null || miCampo.length == 0 || /^\s+$/.test(miCampo)) {
            //$('#' + campo).parent().attr("class", "form-control has-error has-feedback");
            $("#modTitulo").html("Proceso Incompleto");
            $("#modBody").html("Debe ingresar datos de la solicitud.");
            $("#modColHeader").removeClass();
            $("#modColHeader").addClass("modal-header-danger");
            $("#myModal").modal();
            return false;
        } else {

            return true;
        }

    }
    $(document).ready(function () {
        baseUrl = '@Request.Url.Scheme' + '://' + '@Request.Url.Authority';

        $("#nombre").keyup(function () {
            validacion('nombre');
        });


        $("#BtnEnviar").click(function () {

            var v0 = validacion('nombre');
            if(v0){
                $("#modTitulo").html("Proceso Completado");
                $("#modBody").html("Su Solicitud se a subido exitosamente.");
                $("#modColHeader").removeClass();
                $("#modColHeader").addClass("modal-header-success");
                $("#myModal").modal();
            }
        });

        @*$("#buscaRol").click(function () {
            var rol = $("#rol_rol").val();
            var dv = $("#rol_dv").val();
            VerificaRol("@Url.Action("VerificaRol", "Inicio")", rol, dv).done(function (data) {
                $("#listaRol").html("");
                var tipo = typeof data;
                if (tipo === 'string') {
                    $("#modTitulo").html("Validación");
                    $("#modBody").html(data);
                    $("#modColHeader").removeClass();
                    $("#modColHeader").addClass("modal-header-danger");
                    $("#myModal").modal();
                } else if (tipo === 'object') {
                    ListarDeuda(rol, dv);
                }
            });
        });*@

    });
    </script>
}

PagoAseoWeb/Views/Inicio/Mensaje.cshtml
@{
    ViewBag.Title = "Mensaje";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="content">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>@Html.Raw(ViewData["encabezado"].ToString())</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    <p><span class="text-info">Mensaje:</span>&nbsp;&nbsp;@Html.Raw(ViewData["mensaje"].ToString())</p>
                </div>
                <div class="col-md-12">
                    <p><span class="text-info">Recomendación:</span>&nbsp;&nbsp;@Html.Raw(ViewData["recomendacion"].ToString())</p>
                </div>
                <div class="col-md-12">
                    <p><span class="text-info">Motivo:</span>&nbsp;&nbsp;@Html.Raw(ViewData["falla"].ToString())</p>
                </div>
                <div class="col-md-12">
                    <p><span class="text-info">Data:</span>&nbsp;&nbsp;@Html.Raw(ViewData["data"].ToString())</p>
                </div>
                <div class="col-md-12">
                    <p><span class="text-info">Fecha:</span>&nbsp;&nbsp;@Html.Raw(DateTime.Now.ToString())</p>
                </div>
                <div class="col-md-12">
                    <ul class="pager">
                        <li><a href="@Url.Action("Index","Inicio")">Inicio</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
  

PagoAseoWeb/Views/Inicio/listaDeArchivos.cshtml
@model IEnumerable<SocialAseoWeb.Models.TABLE_PARTICULAR_ARCHIVOS_DETALLE>
@using SocialAseoWeb.Comun
@using SocialAseoWeb.Models


<p class="text-danger">Estado del proceso:</p>

<div class="table-responsive">


        <form action="" enctype="multipart/form-data" id="uploadFile" method="post">
            <input type="hidden" name="placaTexHid" id="placaTexHid" value="@placaT">
            <input type="hidden" name="placaNumHid" id="placaNumHid" value="@placaN">
            <input type="hidden" name="correoHid" id="correoHid" value="@correo">
            <input type="hidden" name="fonoHid" id="fonoHid" value="@fono">
            <input type="hidden" name="procesoH" id="procesoH" value="@proceso">
            <input type="hidden" name="clasificacion" id="clasificacion" value="">
            <table class="table table-bordered table-hover">
                <thead><tr class="danger"><th>Tipo Archivo</th>@*<th>Estado</th>*@<th>Archivo</th><th>Subir</th><th>Observación</th></tr></thead>
                <tbody>
       
                        <tr>
                            <td>Padrón</td>
                            @*<td>@padronE</td>*@

                            <td><div class="file-select" id="upload"><input type="file" id="uploadPadron" name="uploadPadron" aria-label="Archivo"></div></td>
                            <td>
                                <input src="img/carga.jpg" type="image" id="btnPadron" name="btnPadron" value="" onclick="">
                            </td>
                            <td>@msgPadron</td>
                        </tr>
                  
                  
                        <tr>
                            <td>P. Circulación</td>
                            @*<td>@perCirE</td>*@

                            <td><div class="file-select" id="upload"><input type="file" id="uploadPC" name="uploadPC" aria-label="Archivo"></div></td>
                            <td><input src="img/carga.jpg" type="image" id="btnPC" name="btnPC" value="▲" onclick=""></td>
                            <td>@msgPerCir</td>
                        </tr>
                  
                        <tr>
                            <td>SOAP</td>
                            @*<td>@soapE</td>*@

                            <td><div class="file-select" id="upload"><input type="file" id="uploadSoap" name="uploadSoap" aria-label="Archivo"></div></td>
                            <td><input src="img/carga.jpg" type="image" id="btnSoap" name="btnSoap" value="▲" onclick=""></td>
                            <td>@msgSoap</td>
                        </tr>
                 
                        <tr id="revTec">
                            <td>R. Técnica</td>
                            @*<td>@revTecE</td>*@

                            <td><div class="file-select" id="upload"><input type="file" id="uploadRTec" name="uploadRTec" aria-label="Archivo"></div></td>
                            <td><input src="img/carga.jpg" type="image" id="btnRTec" name="btnRTec" value="▲" onclick=""></td>
                            <td>@msgRevTec</td>
                        </tr>
                 
                        <tr>
                            <td>R. Gases</td>
                            @*<td>@revGasE</td>*@

                            <td><div class="file-select" id="upload"><input type="file" id="uploadRGas" name="uploadRGas" aria-label="Archivo"></div></td>
                            <td><input src="img/carga.jpg" type="image" id="btnRGas" name="btnRGas" value="▲" onclick=""></td>
                            <td>@msgRevGas</td>
                        </tr>
                
                        <tr>
                            <td>C. Homologación</td>
                            @*<td>@cerHomE</td>*@

                            <td><div class="file-select" id="upload"><input type="file" id="uploadCerHom" name="uploadCerHom" aria-label="Archivo"></div></td>
                            <td><input src="img/carga.jpg" type="image" id="btnCerHom" name="btnCerHom" value="▲" onclick=""></td>
                            <td>@msgCerHom</td>
                        </tr>
                
                        <tr>
                            <td>Factura</td>
                            @*<td>@facturE</td>*@

                            <td><div class="file-select" id="upload"><input type="file" id="uploadFact" name="uploadFact" aria-label="Archivo"></div></td>
                            <td><input src="img/carga.jpg" type="image" id="btnFact" name="btnFact" value="▲" onclick=""></td>
                            <td>@msgfactura</td>
                        </tr>
                  
                        <tr>
                            <td>Solicitud Reg. Civil</td>
                            @*<td>@regCivilE</td>*@

                            <td><div class="file-select" id="upload"><input type="file" id="uploadRegCivil" name="uploadRegCivil" aria-label="Archivo"></div></td>
                            <td><input src="img/carga.jpg" type="image" id="btnRegCivil" name="btnRegCivil" value="▲" onclick=""></td>
                            <td>@msgRegCiv</td>
                        </tr>
                 
                        <tr>
                            <td>Cert. Inscrip. Seremi de Transportes</td>
                            @*<td>@certSeremiE</td>*@

                            <td><div class="file-select" id="upload"><input type="file" id="uploadCertSeremi" name="uploadCertSeremi" aria-label="Archivo"></div></td>
                            <td><input src="img/carga.jpg" type="image" id="btnCertSeremi" name="btnCertSeremi" value="▲" onclick=""></td>
                            <td>@msgCertSeremi</td>
                        </tr>
                    
                </tbody>
            </table>
        </form>
    

</div>