PagoAseoWeb/Controllers/PagoController.cs
using CrystalDecisions.CrystalReports.Engine;
using SocialAseoWeb.Comun;
using SocialAseoWeb.Models;
using SocialAseoWeb.PagosMacul;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Net.Security;
using System.Security.Cryptography.X509Certificates;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Transbank.NET.sample.certificates;
//using Webpay.Transbank.Library;
//using Webpay.Transbank.Library.Wsdl.Normal;
//using Webpay.Transbank.Library.Wsdl.Nullify;
using Transbank.Webpay;
using Transbank.Webpay.Wsdl.Normal; 

namespace SocialAseoWeb.Controllers
{
    public class PagoController : BaseController
    {

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult VerificaDeuda(string rol, string dv)
        {
            LogReg log = new LogReg();
            
            decimal numRol = 0;
            decimal numDv = 0;
            string rolLog = rol + "-" + dv;
            List<AS_PAGOS> deudas = new List<AS_PAGOS>();

            try
            {
                log.abrirArchivo(rolLog);
                log.registrar("*********************************************");
                log.registrar(" * PROCESO: VerificaDeuda");
                log.registrar("*********************************************");
                bool valRol = decimal.TryParse(rol, out numRol);
                bool valDv = decimal.TryParse(dv, out numDv);
                if (valRol == false || valDv == false)
                {
                    return Json("El rol se compone de números. Debe Ingresar datos validos.");
                }


                using (aseoEntities entidadesAseo = new aseoEntities())
                {

                    var d = entidadesAseo.AS_PAGOS.Where(x => x.PAG_FEC_P == null && x.PAG_ROL_NUM == numRol && x.PAG_ROL_DV == numDv && x.PAG_MARCA != "C").ToList();
                    if (DateTime.Now.Month < 9)
                    {
                        d = d.Where(x => x.PAG_ANO_CON != DateTime.Now.Year).ToList();
                    }
                    foreach (AS_PAGOS p in d)
                    {
                        /*verifica si exento*/
                        var convenio = entidadesAseo.AS_CONVENIO.Where(x => x.CON_ANO_CON == p.PAG_ANO_CON && x.CON_ROL_NUM == p.PAG_CUOTA && x.CON_ROL_NUM == p.PAG_ROL_NUM && x.CON_ROL_DV == p.PAG_ROL_DV).FirstOrDefault();

                        if (convenio == null)
                        {
                            return Json(new Object());
                        }
                        else if (convenio.CON_CODEX.Equals(5) || convenio.CON_CODEX.Equals(6) || convenio.CON_CODEX.Equals(7))
                        {

                        }
                        else
                        {
                            return Json(new Object());
                        }

                    }

                }
                
            }
            catch (Exception ex)
            {
                string ns = this.ControllerContext.Controller.GetType().Namespace;
                string controller = this.ControllerContext.RouteData.Values["controller"].ToString();
                string action = this.ControllerContext.RouteData.Values["action"].ToString();
                ManejoErrores(ns, controller, action, ex, log);
            }
            return Json("No hay una deuda asociada con el Rol ingresado.");
           
        }

        [HttpGet]
        public PartialViewResult ListarDeuda(string rol, string dv) {

            LogReg log = new LogReg();
            decimal numRol = 0;
            decimal numDv = 0;
            string rolLog = rol + "-" + dv;
            List<AS_PAGOS> deudas = new List<AS_PAGOS>();
            try
            {
                log.abrirArchivo(rolLog);
                log.registrar("*********************************************");
                log.registrar(" * PROCESO: ListarDeuda");
                log.registrar("*********************************************");
                bool valRol = decimal.TryParse(rol, out numRol);
                bool valDv = decimal.TryParse(dv, out numDv);

                if (valRol == false || valDv == false)
                {
                    return PartialView(deudas);
                }

                using (aseoEntities entidadesAseo = new aseoEntities())
                {
                    var d = entidadesAseo.AS_PAGOS.Where(x => x.PAG_FEC_P == null && x.PAG_ROL_NUM == numRol && x.PAG_ROL_DV == numDv && x.PAG_MARCA != "C").OrderBy(x => x.PAG_CUOTA).OrderBy(x => x.PAG_ANO_CON).ToList();
                    if (DateTime.Now.Month < 9)
                    {
                        d = d.Where(x => x.PAG_ANO_CON != DateTime.Now.Year).ToList();
                    }
                    foreach (AS_PAGOS p in d)
                    {
                        bool siExento = false;
                        /*verifica si exento*/
                        var convenio = entidadesAseo.AS_CONVENIO.Where(x => x.CON_ANO_CON == p.PAG_ANO_CON && x.CON_ROL_NUM == p.PAG_CUOTA && x.CON_ROL_NUM == p.PAG_ROL_NUM && x.CON_ROL_DV == p.PAG_ROL_DV).FirstOrDefault();

                        if (convenio == null)
                        {

                        }
                        else if (convenio.CON_CODEX.Equals(5) || convenio.CON_CODEX.Equals(6) || convenio.CON_CODEX.Equals(7))
                        {
                            siExento = true;
                        }


                        if (siExento == false)
                        {
                            if (p.PAG_VALOR > 0)
                            {
                                decimal anioActual = DateTime.Now.Year;
                                decimal mesActual = DateTime.Now.Month;
                                decimal valor = decimal.Parse(p.PAG_VALOR.ToString());
                                decimal facIpc = FUNCIONES_DDBB.FN_OBT_IPC(mesActual, anioActual, p.PAG_FEC_V.Value.Month, p.PAG_FEC_V.Value.Year);
                                decimal facMul = FUNCIONES_DDBB.FN_OBT_MULTA(mesActual, anioActual, p.PAG_FEC_V.Value.Month, p.PAG_FEC_V.Value.Year);
                                decimal ipc = decimal.Round((valor * facIpc) / 100, 0);
                                decimal multa = decimal.Round(((valor + ipc) * facMul) / 100);

                                decimal ipcF = (decimal.Round(ipc % 2, 1) == 0.5m) ? 0.1m : 0;
                                decimal multaF = (decimal.Round(multa % 2, 1) == 0.5m) ? 0.1m : 0;

                                ipc = ipc + ipcF;
                                multa = multa + multaF;
                                p.INTERES = decimal.Round(ipc, 0);
                                p.MULTA = decimal.Round(multa, 0);
                                p.TOTAL = decimal.Round(decimal.Parse(p.PAG_VALOR.ToString()) + p.INTERES + p.MULTA, 0);

                                p.PAG_IPC = decimal.Round(ipc, 0);
                                p.PAG_MULTA = decimal.Round(multa, 0);
                                p.PAG_TOTAL = decimal.Round(decimal.Parse(p.PAG_VALOR.ToString()) + p.INTERES + p.MULTA, 0);
                                entidadesAseo.SaveChanges();
                                deudas.Add(p);

                            }
                        }

                    }
                }
            }
            catch (Exception ex)
            {
                string ns = this.ControllerContext.Controller.GetType().Namespace;
                string controller = this.ControllerContext.RouteData.Values["controller"].ToString();
                string action = this.ControllerContext.RouteData.Values["action"].ToString();
                ManejoErrores(ns, controller, action, ex, log);

            }
           
           
            return PartialView(deudas);
        }
        [HttpGet]
        public PartialViewResult ListarRol(string rol, string dv)
        {

            LogReg log = new LogReg();
            decimal numRol = 0;
            decimal numDv = 0;
            string rolLog = rol + "-" + dv;
            List<AS_CONVENIO> deudas = new List<AS_CONVENIO>();
            try
            {
                log.abrirArchivo(rolLog);
                log.registrar("*********************************************");
                log.registrar(" * PROCESO: Listar");
                log.registrar("*********************************************");
                bool valRol = decimal.TryParse(rol, out numRol);
                bool valDv = decimal.TryParse(dv, out numDv);

                if (valRol == false || valDv == false)
                {
                    return PartialView(deudas);
                }

                using (aseoEntities entidadesAseo = new aseoEntities())
                {
                    var d = entidadesAseo.AS_CONVENIO.Where(x => x.CON_ROL_NUM == numRol && x.CON_ROL_DV == numDv && x.CON_MARCA != "S").OrderBy(x => x.CON_CUOTA).OrderBy(x => x.CON_ANO_CON).ToList();
                    if (DateTime.Now.Month < 9)
                    {
                        d = d.Where(x => x.CON_ANO_CON != DateTime.Now.Year).ToList();
                    }
                    foreach (AS_CONVENIO p in d)
                    {
                        bool siExento = false;
                        /*verifica si exento*/
                        //var convenio = entidadesAseo.AS_CONVENIO.Where(x => x.CON_ANO_CON == p.PAG_ANO_CON && x.CON_ROL_NUM == p.PAG_CUOTA && x.CON_ROL_NUM == p.PAG_ROL_NUM && x.CON_ROL_DV == p.PAG_ROL_DV).FirstOrDefault();

                        //if (convenio == null)
                        //{

                        //}
                        //else if (convenio.CON_CODEX.Equals(5) || convenio.CON_CODEX.Equals(6) || convenio.CON_CODEX.Equals(7))
                        //{

PagoAseoWeb/Views/Pago/ConfirmarDeuda.cshtml
@model SocialAseoWeb.Models.OrdenIngresoAseo
@using System.Globalization
@{
    ViewBag.Title = "Confirmar Deuda";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class='panel panel-default'>
    <div class="panel-heading"><h4 style="color: #E5006C; text-align:center;font-weight:600;">OPCIONES DE PAGO</h4></div>
    <div class='panel-body'>
        <div class="row">
            <div class="col-md-2">
                <form method ="post" action="@Url.Action("TransbankNew", "Pago")" id="envioPagoTBK">
                    <button name="btnConfirmar" class="btn" type="submit"><img alt="" src="~/Img/BTN_TBK.jpg" class="img-responsive" /></button>
                    <input name='rolNum' id='rolNumTGR' type='hidden' value="@Html.Raw(Model.rolNum.ToString())" />
                    <input name='rolDv' id='rolDvTGR' type='hidden' value="@Html.Raw(Model.rolDv.ToString())" />
                    <input name='telefono' id='telefonoTGR' type='hidden' value="@Html.Raw(Model.telefono.ToString())" />
                    <input name='email' id='eMailTGR' type='hidden' value="@Html.Raw(Model.eMail.ToString())" />
                    @for (int row = 0; row < Model.DOI.Count; row++)
                    {
                        <input name='deuda' type='hidden' value="@Html.Raw(Model.DOI[row].anio + "_" + Model.DOI[row].cuota)" />
                    }
                </form>
            </div>
            <div class="col-md-2">
                @*
                    <form style="color: rgba(48, 50, 128, 1); float: right;" method="post" action="" id="envioPagoTGR">
                        <strong><font size=1>En caso de problemas con el pago</font><input name="btnConfirmar" type="submit" class="btn btn-link" value="Click aqui" /></strong>
                        <input name="rol" type="hidden" value="" />
                        <input name="email" type="hidden" value="" />
                        <input name="telefono" type="hidden" value="" />
                        <input name="ordIngreso" type="hidden" value="" />
                    </form>
                *@
            </div>
            <div class="col-md-8"></div>
        </div>

    </div>
</div>
<div class='panel panel-default'>
    <div class="panel-heading"><h4 style="color: #E5006C; text-align:center;font-weight:600;">DATOS DEL PAGO</h4></div>
    <div class='panel-body'>
        <div class="row">
            <div class="col-md-4">
                <span style="color: #E5006C;">RUT</span>
                &nbsp;&nbsp;&nbsp;&nbsp;<p>@Html.Raw(Model.rut + "-" + Model.dv)</p>
            </div>
            <div class="col-md-4">
                <span style="color: #E5006C;">NOMBRE(RAZON SOCIAL)</span>
                &nbsp;&nbsp;&nbsp;&nbsp;<p>@Html.Raw(Model.nombre)</p>
            </div>
            <div class="col-md-4">
                <span style="color: #E5006C;">FECHA GIRO</span>
                &nbsp;&nbsp;&nbsp;&nbsp;<p>@Html.Raw((DateTime.Now).ToString("dd-MM-yyyy"))</p>
            </div>
            <div class="col-md-4">
                <span style="color: #E5006C;">DOMICILIO</span>
                &nbsp;&nbsp;&nbsp;&nbsp;<p>@Html.Raw(Model.direccion)</p>
            </div>
            <div class="col-md-4">
                <span style="color: #E5006C;">CUIDAD</span>
                &nbsp;&nbsp;&nbsp;&nbsp;<p>@Html.Raw(Model.cuidad)</p>
            </div>
            <div class="col-md-4">
                <span style="color: #E5006C;">ROL</span>
                &nbsp;&nbsp;&nbsp;&nbsp;<p>@Html.Raw(Model.rolNum + "-" + Model.rolDv)</p>
            </div>
            <div class="col-md-4">
                <span style="color: #E5006C;">TELÉFONO</span>
                &nbsp;&nbsp;&nbsp;&nbsp;<p>@Html.Raw(Model.telefono)</p>
            </div>
            <div class="col-md-4">
                <span style="color: #E5006C;">E-MAIL</span>
                &nbsp;&nbsp;&nbsp;&nbsp;<p>@Html.Raw(Model.eMail)</p>
            </div>
            <div class="col-md-4">
                <span style="color: #E5006C;">TIPO DE TRIBUTO</span>
                &nbsp;&nbsp;&nbsp;&nbsp;<p>@Html.Raw(Model.tipoTributo)</p>
            </div>
            
            <div class="col-md-12 table-responsive">
                <hr style="border-top: 1px solid #E5006C;" />
                <table class="table table-bordered">
                    <thead>
                        <tr class="danger">
                            <th>DENOMINACIÓN</th>
                            <th>FECHA DE VENCIMIENTO</th>
                            <th>VALOR A PAGAR</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.DOI)
                        {
                            <tr>
                                <td>
                                    <p> @Html.DisplayFor(modelItem => item.denominacion)</p>
                                </td>
                                <td>
                                    <p>  @Html.DisplayFor(modelItem => item.fecVence) </p>
                                </td>
                                <td>
                                    <p>  @Html.Raw("$" + String.Format(System.Globalization.CultureInfo.CreateSpecificCulture("es-CO"), "{0:N0}", Convert.ToDecimal(item.monto)))</p>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

            <div class="col-md-12 well">
                <div class="row">
                    <div class="col-md-3">
                        <span style="color: #E5006C;">SUBTOTAL</span>
                        &nbsp;&nbsp;&nbsp;&nbsp;<p>@Html.Raw("$" + String.Format(System.Globalization.CultureInfo.CreateSpecificCulture("es-CO"), "{0:N0}", Convert.ToDecimal(@Model.subtotal)))</p>
                    </div>
                    <div class="col-md-3">
                        <span style="color: #E5006C;">IPC</span>
                        &nbsp;&nbsp;&nbsp;&nbsp;<p>@Html.Raw("$" + String.Format(System.Globalization.CultureInfo.CreateSpecificCulture("es-CO"), "{0:N0}", Convert.ToDecimal(@Model.ipc)))</p>
                    </div>
                    <div class="col-md-3">
                        <span style="color: #E5006C;">MULTAS</span>
                        &nbsp;&nbsp;&nbsp;&nbsp;<p>@Html.Raw("$" + String.Format(System.Globalization.CultureInfo.CreateSpecificCulture("es-CO"), "{0:N0}", Convert.ToDecimal(@Model.multa)))</p>
                    </div>
                    <div class="col-md-3">
                        <span style="color: #E5006C;">TOTAL</span>
                        &nbsp;&nbsp;&nbsp;&nbsp;<p>@Html.Raw("$" + String.Format(System.Globalization.CultureInfo.CreateSpecificCulture("es-CO"), "{0:N0}", Convert.ToDecimal(@Model.aPagar)))</p>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</div>

@section scripts{

    @*<script type="text/javascript">
            window.onload = function () {
                localStorage = window.localStorage;
               // alert(localStorage.getItem('test'));
                if (localStorage.getItem('test') == '1') {
                    localStorage.setItem('test', 0);
                    window.location.href = '@Url.Action("Fracaso", "Pago")';
                }
            }
            $(document).ready(function () {
                $('form').submit(function () {
                    localStorage.setItem('test', 1);
                });
            });

        </script>
    *@
}
   

PagoAseoWeb/Views/Pago/Exito.cshtml
@model SocialAseoWeb.Models.OrdenIngresoAseo
@using System.Web.Script.Serialization
@using SocialAseoWeb.Models
@using SocialAseoWeb.Comun


@{
    ViewBag.Title = "Portal de Derechos de Aseo";
    Layout = "~/Views/Shared/_Layout.cshtml";
    JavaScriptSerializer jss = new JavaScriptSerializer();
}


    <form id="formPago">
        <div class="row">
            <div class="col-md-12">
                <p>No se realizan devoluciones, ni reembolsos. En caso de tener alguna duda favor de contactar a @Html.Raw(Utils.adminContacto) al teléfono @Utils.telefono  o al  Correo Electronico @Utils.adminEMail.</p>
                <p>Los comprobantes de pago no se envian a una casilla electrónica. Solo se pueden obtener en este sitio.</p>
                <div id="DatContribuyente" class="panel panel-default">
                    <div class="panel-heading">Datos del Contribuyente</div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-2">RUT:</div>
                            <div class="col-md-4"><div id="rutP" class="text-success">@Html.Raw(Model.rut.ToString() + "-" + Model.dv)</div></div>
                            <div class="col-md-2">NOMBRE:</div>
                            <div class="col-md-4"><div id="nombreP" class="text-success">@Html.Raw(Model.nombre)</div></div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">DOMICILIO:</div>
                            <div class="col-md-4"><div id="domicilioP" class="text-success">@Html.Raw(Model.direccion)</div></div>
                            <div class="col-md-2">CUIDAD:</div>
                            <div class="col-md-4"><div id="comunaP" class="text-success">@Html.Raw(Model.cuidad)</div></div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">TÉLEFONO:</div>
                            <div class="col-md-4"><div id="telPar" class="text-success">@Html.Raw(Model.telefono)</div></div>
                            <div class="col-md-2">E-MAIL:</div>
                            <div class="col-md-4"><div id="emailPar" class="text-success">@Html.Raw(Model.eMail)</div></div>
                        </div>
                        <div class="row">
                            <div class="col-md-2">N° ORDEN:</div>
                            <div class="col-md-4"><div id="canPlaPar" class="text-success">@Html.Raw(Model.nOrden)</div></div>
                            <div class="col-md-2"></div>
                            <div class="col-md-4"><div id="nOrdenPlaPar" class="text-success"></div></div>

                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <p id="menCont" style="color:red;font-weight: bold;"></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <input id="buscaPago" name="buscaPago" class="btn btn-danger btn-block"  value="Ver Comprobante" />
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div id="listaPagadas"></div>
            </div>
        </div>
        <br />
    </form>
@section Scripts{
    <script type="text/javascript">
        var baseUrl = "";
        $(document).ready(function () {
            baseUrl = '@Request.Url.Scheme' + '://' + '@Request.Url.Authority';
            OI = '@Html.Raw(jss.Serialize(Model))';
            OIdata = JSON.parse(OI);
            var rol = OIdata.rolNum;
            var dv = OIdata.rolDv;
            var folio = OIdata.nOrden;
            $("#buscaPago").click(function () {
                ValidaPagoTBK("@Url.Action("ValidaPagoTBK", "Pago")", folio).done(function (data) {
                    $("#listaPagadas").html("");
                    if (data == "PAGADO") {
                        listarArchivos(rol, dv, folio);
                    } else if (data == "ADEUDADO") {
                        $("#listaPagadas").html("<br /><p>Se produjo un error al momento de ejecutar el pago, comuniquese con el administrador del sitio.</p>");
                    } else if (data == "RECHAZADO") {
                        $("#listaPagadas").html("El pago ha sido rechazado por la entidad bancaria, intentelo con otro medio de pago");
                    } else {
                        alert("se ha producido un error: " + data);
                    }
                });
            });

        });
    </script>

    <script type="text/javascript">
        function listarArchivos(rolT, dvT, folioT) {
            var miUrl = '@Url.Action("MuestraReporte", "Pago", new { rol = "rolText", dv = "dvText", folio = "folioText" })'.replace("rolText", rolT).replace("dvText", dvT).replace("folioText", folioT);
            miUrl = miUrl.replace("&amp;", "&");
            miUrl = miUrl.replace("&amp;", "&");
            $("#listaPagadas").html(" <br /><iframe width='100%' height='800px' src='" + miUrl + "'></iframe>");;
       }

        function ValidaPagoTBK(baseUrl, folio, rol) {
            url = baseUrl;
            return $.ajax({
                url: url,
                method: 'POST',
                async: false,
                dataType: 'json',
                data: {
                    folio: folio
                },
                success: function (data, textStatus, xhr) {

                },
                error: function (request, status, error) {
                    console.log(request.responseText);
                    alert("Error has occurred..." + request.responseText);
                }
            });
        }
    </script>
}

PagoAseoWeb/Views/Pago/Index.cshtml
@using SocialAseoWeb.Comun
@{
    ViewBag.Title = "Derecho de Aseo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@*************************** formulario busqueda ********************************@
<div class="well">
    <h1 style="color: #E5006C; text-align:center;font-weight:600;">Consultar Rol Propiedad</h1>
    <div class="row">
        <div class="col-md-1"></div>
        <div class="well col-md-10" style="background-color:white">
            <p>Ingrese el Rol de la Propiedad correspondiente al derecho de aseo que desea consultar.</p>
            <hr style="border-top: 1px solid #E5006C;" />
            <form id="formBuscar" class="text-center" action="./">
                <div class="row">
                    <div class="col-md-8">
                        <div class="input-group">
                            <span style="font: bold 14px Arial;" class="input-group-addon">ROL:</span>
                            <input id="rol_rol" type="text" class="form-control" name="rol_rol" placeholder="0000" maxlength="4">
                            <span style="font: bold 14px Arial;" class="input-group-addon"> - </span>
                            <input id="rol_dv" type="text" class="form-control" name="rol_dv" placeholder="0000" maxlength="4">
                        </div>
                    </div>
                    <div class="col-md-4">
                        <input id="buscaRol" name="buscaRol" type="button" value="Buscar" class="btn btn-danger btn-block" />
                    </div>
                </div>
            </form>

        </div>
        <div class="col-md-1"></div>
    </div>
</div>
<div style="text-align:left" id='mensaBuscar'></div>
<div id="listaRol"></div>
@section scripts{
    <script type="text/javascript">
        var baseUrl = "";
        $(document).ready(function () {
            baseUrl = '@Request.Url.Scheme' + '://' + '@Request.Url.Authority';
            $("#buscaRol").click(function () {
                var rol = $("#rol_rol").val();
                var dv = $("#rol_dv").val();
                VerificaRol("@Url.Action("VerificaDeuda", "Pago")", rol, dv).done(function (data) {
                    $("#listaRol").html("");
                    var tipo = typeof data;
                    if (tipo === 'string') {
                        $("#modTitulo").html("Validación");
                        $("#modBody").html(data);
                        $("#modColHeader").removeClass();
                        $("#modColHeader").addClass("modal-header-danger");
                        $("#myModal").modal();
                    } else if (tipo === 'object') {
                        ListarRol(rol, dv);
                    }
                });
            });

        });

        function ListarRol(rol, dv) {
            var url = '@Url.Action("ListarDeuda", "Pago", new { rol = "rolText", dv = "dvText" })';
            url = url.replace("rolText", rol);
            url = url.replace("dvText", dv);
            url = url.replace("&amp;", "&");
            $("#listaRol").load(url);
        }

        function VerificaRol(baseUrl, rol, dv) {
            url = baseUrl;
            return $.ajax({
                url: url,
                method: 'POST',
                async: false,
                dataType: 'json',
                data: {
                    rol: rol,
                    dv: dv
                },
                success: function (data, textStatus, xhr) {

                },
                error: function (request, status, error) {
                    console.log(request.responseText);
                    alert("Error has occurred..." + request.responseText);
                }
            });
        }


    </script>

}

PagoAseoWeb/Views/Pago/Tesoreria.cshtml
@model SocialAseoWeb.Models.OrdenIngresoAseo

@{
    ViewBag.Title = "Portal de Pago de Tesoreria";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>Para realizar el pago de los derechos de aseo debe tener habilitadas las cookies de su navegador</p>
<iframe width="100%" height="800px" src="@Url.Action("EnviarPagoTesoreria", "Pago", new { rolNum = Model.rolNum, rolDv = Model.rolDv, sesion = Model.idSesion, nOrden = Model.nOrden })" id="content"></iframe>

PagoAseoWeb/Views/Pago/Transbank.cshtml
@model SocialAseoWeb.Models.OrdenIngresoAseo

@{
    ViewBag.Title = "Transbank";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>Para realizar el pago de los derechos de aseo debe tener habilitadas las cookies de su navegador</p>
<iframe width="100%" height="800px" src="@Url.Action("EnviarPagoTransbank", "Pago", new { rolNum = Model.rolNum, rolDv = Model.rolDv, sesion = Model.idSesion, nOrden = Model.nOrden })" id="content"></iframe>

PagoAseoWeb/Views/Pago/TransbankNew.cshtml
@model SocialAseoWeb.Models.OrdenIngresoAseo

@{
    ViewBag.Title = "Transbank";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>Para realizar el pago de los derechos de aseo debe tener habilitadas las cookies de su navegador</p>
<iframe width="100%" height="800px" src="@Url.Action("EnviarPagoTransbankNew", "Pago", new { rolNum = Model.rolNum, rolDv = Model.rolDv, sesion = Model.idSesion, nOrden = Model.nOrden })" id="content"></iframe>